// src/components/TradePanel.tsx

import React, { useState } from 'react';
import { createTrade } from '@/lib/supabase/service'; 
import { useRouter } from 'next/navigation'; 
import { SupabaseClient } from '@supabase/supabase-js';

// NOTE: Defining formatters locally for simplicity, but best practice is to import from '@/lib/utils/formatters'
const localFormatCurrency = (value: number) => {
    const numValue = typeof value === 'number' ? value : 0;
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(numValue);
};


interface TradePanelProps {
    coinId: string;
    coinSymbol: string;
    currentPrice: number;
    cashBalance: number; // Passed from parent (page.tsx)
    onTradeSuccess: () => void;
    supabase: SupabaseClient;
}

export default function TradePanel({ coinId, coinSymbol, currentPrice, cashBalance, onTradeSuccess, supabase }: TradePanelProps) {
    const [usdAmount, setUsdAmount] = useState<number | ''>('');
    const [isBuying, setIsBuying] = useState(true);
    const [isProcessing, setIsProcessing] = useState(false);
    const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

    const router = useRouter();

    const cryptoAmount = typeof usdAmount === 'number' && currentPrice > 0 
        ? usdAmount / currentPrice 
        : 0;

    const handleTrade = async (type: 'BUY' | 'SELL') => {
        if (typeof usdAmount !== 'number' || usdAmount <= 0) {
            setMessage({ type: 'error', text: 'Please enter a valid amount.' });
            return;
        }

        if (type === 'BUY' && usdAmount > cashBalance) {
             setMessage({ type: 'error', text: 'Insufficient cash balance for this purchase.' });
             return;
        }

        setIsProcessing(true);
        setMessage(null);

        try {
            const tradeData = {
                coin_id: coinId,
                coin_symbol: coinSymbol,
                type: type,
                fiat_amount: usdAmount,
                crypto_amount: cryptoAmount,
                execution_price: currentPrice,
                // Note: executed_at is generated by the service/database layer
            };

            // Call the core service function
            await createTrade(supabase, tradeData, type === 'BUY');
            
            setMessage({ 
                type: 'success', 
                text: `${type} successful! You ${type === 'BUY' ? 'purchased' : 'sold'} ${cryptoAmount.toFixed(5)} ${coinSymbol}.` 
            });
            setUsdAmount('');
            onTradeSuccess(); // Trigger data refresh on the parent page
            router.refresh(); // THIS is what forces ProfileBarServer to re-run

        } catch (error: any) {
            // Display error message from service layer (e.g., insufficient funds)
            setMessage({ type: 'error', text: `Trade failed: ${error.message || 'Unknown error'}` });
        } finally {
            setIsProcessing(false);
        }
    };

    const actionText = isBuying ? 'Execute BUY' : 'Execute SELL';
    const actionColor = isBuying ? 'bg-blue-600 hover:bg-blue-700' : 'bg-red-600 hover:bg-red-700';

    return (
        <div className="bg-white p-6 rounded-xl shadow-2xl space-y-4">
            <h2 className="text-xl font-bold text-gray-800 border-b pb-3">Trade {coinSymbol}</h2>

            {/* Buy/Sell Selector */}
            <div className="flex bg-gray-100 rounded-lg p-1">
                <button
                    onClick={() => setIsBuying(true)}
                    className={`flex-1 py-2 text-sm font-semibold rounded-lg transition ${
                        isBuying ? 'bg-blue-600 text-white shadow-md' : 'text-gray-600 hover:bg-gray-200'
                    }`}
                    disabled={isProcessing}
                >
                    BUY
                </button>
                <button
                    onClick={() => setIsBuying(false)}
                    className={`flex-1 py-2 text-sm font-semibold rounded-lg transition ${
                        !isBuying ? 'bg-red-600 text-white shadow-md' : 'text-gray-600 hover:bg-gray-200'
                    }`}
                    disabled={isProcessing}
                >
                    SELL
                </button>
            </div>

            {/* Input Form */}
            <div className="space-y-3">
                
                {/* Available Balance Display */}
                <div className="text-sm font-medium text-gray-500">
                    Available Cash: 
                    <span className="font-bold text-gray-900 ml-1">
                        {localFormatCurrency(cashBalance)}
                    </span>
                </div>

                {/* USD Input */}
                <label className="block text-sm font-medium text-gray-700">Amount in USD to {isBuying ? 'Spend' : 'Receive'}:</label>
                <input
                    type="number"
                    step="0.01"
                    min="0"
                    value={usdAmount}
                    onChange={(e) => setUsdAmount(parseFloat(e.target.value) || '')}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 transition"
                    placeholder="Enter USD amount"
                    disabled={isProcessing}
                />

                {/* Crypto Conversion Display */}
                <div className="text-sm text-gray-600 p-2 bg-gray-50 rounded-lg border border-dashed">
                    You will {isBuying ? 'acquire' : 'sell'}: 
                    <span className="font-semibold text-gray-900 ml-1">
                        {cryptoAmount.toFixed(6)} {coinSymbol}
                    </span>
                </div>

                {/* Current Price Reference */}
                <div className="text-xs text-gray-500 pt-1">
                    Executed at: {localFormatCurrency(currentPrice)}
                </div>

                {/* Message Box */}
                {message && (
                    <div
                        className={`p-3 text-sm rounded-lg shadow-sm ${
                            message.type === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                        }`}
                    >
                        {message.text}
                    </div>
                )}

                {/* Action Button */}
                <button
                    onClick={() => handleTrade(isBuying ? 'BUY' : 'SELL')}
                    disabled={isProcessing || typeof usdAmount !== 'number' || usdAmount <= 0}
                    className={`w-full py-3 rounded-xl font-bold transition shadow-lg ${
                        isProcessing 
                            ? 'bg-gray-400 cursor-not-allowed'
                            : `${actionColor} text-white`
                    }`}
                >
                    {isProcessing ? 'Processing...' : actionText}
                </button>
            </div>
        </div>
    );
}